# Generated by Django 2.1.7 on 2019-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[(1, 'a'), (2, 'b'), (3, 'c')], max_length=3)),
            ],
        ),
    ]
