# Generated by Django 2.1.7 on 2019-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='brand',
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.CharField(choices=[(1, 'a'), (2, 'b'), (3, 'c')], default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='issue',
            field=models.CharField(choices=[(1, 'a'), (2, 'b'), (3, 'c')], default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='printer',
            field=models.CharField(choices=[(1, 'a'), (2, 'b'), (3, 'c')], default=1, max_length=3),
        ),
    ]
