# Generated by Django 2.1.7 on 2019-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printermanagement', '0002_auto_20190331_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='issue',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='printer',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
